// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'red': string;
  'sidebar': string;
  'sidebar-heading': string;
  'sidebar-sticky': string;
}
export const cssExports: CssExports;
export default cssExports;
