// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'close': string;
  'main-window': string;
  'red': string;
  'relative': string;
  'sidebar': string;
  'sidebar-heading': string;
  'sidebar-sticky': string;
  'tab-bar': string;
}
export const cssExports: CssExports;
export default cssExports;
