// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'circle': string;
  'circle--animation': string;
  'spin': string;
  'spinner': string;
  'svg': string;
  'svg--animation': string;
}
export const cssExports: CssExports;
export default cssExports;
