theme: jekyll-theme-cayman
title: TrenDAP
description: Trending Data Analytics Platform
github:
  repository_name: GridProtectionAlliance/TrenDAP
  owner_url: https://www.gridprotectionalliance.org
  owner_name: Grid Protection Alliance
plugins:
  - jemoji
